baseurl: /
<<<<<<< HEAD
title: ZuS-Sec
=======
title: who knows?
>>>>>>> 247187d (new post)
theme: photophobia
sectionPagesMenu: main
Params:
  favicon: null
  site_logo: null
  description:  ""
  recent_posts_number: 10
<<<<<<< HEAD
  author: Thwin Htet Win a.k.a ZuS
=======
  author: Thwin Htet Win
>>>>>>> 247187d (new post)
  mainSections:
    - post
  intro: true
  description: 'someone in the crowd'
  github: 'https://github.com/ThwinHtetWin'
  twitter: 'https://twitter.com/thwinhtet_'
  email: 'thwinhtetwin.me@gmail.com'
  opengraph: true
  shareTwitter: true
  dateFormat: 'Mon, Jan 2, 2006'
Permalinks:
  post: '/:filename/'

markup:
  highlight:
    style: native

taxonomies:
  category: "categories"

menu:
  nav:
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: connect
      name: Connect
      url: /connect/
      weight: 3

